<?PHP
session_cache_expire(30);
session_start();

require_once('header.php');


$loggedIn = false;
    $accessLevel = 0;
    $userID = null;
    $isAdmin = false;

    require_once('database/dbUsers.php');

    if (!isset($_SESSION['access_level']) || $_SESSION['access_level'] < 1) {
        header('Location: login.php');
        die();
    }
    if (isset($_SESSION['_id'])) {
        $loggedIn = true;
        // 0 = not logged in, 1 = student, 3 instructor
        $accessLevel = $_SESSION['access_level'];
        $isAdmin = $accessLevel >= 2;
        $userID = $_SESSION['_id'];
    } else {
        header('Location: login.php');
        die();
    }
    if ($isAdmin && isset($_GET['id'])) {
        require_once('include/input-validation.php');
        $args = sanitize($_GET);
        $id = strtolower($args['id']);
    } else {
        $id = $userID;
    }
    if (isset($_GET['removePic'])) {
      if ($_GET['removePic'] === 'true') {
        remove_profile_picture($id);
      }
    }

    $user = retrieve_user($id);
    $viewingOwnProfile = $id == $userID;

?>
<!-- page generated by the BowdoinRMH software package -->
<html>
    <head>
        <meta HTTP-EQUIV="REFRESH" contento="2; url=deleteUserSearch.php">
        <?php require('universal.inc') ?>
    </head>
    <body>
        <nav>
            <span id="nav-top">
                <span class="logo">
                    <img src="<?php include('logo.php'); ?>">
                        <span id="vms-logo">Volunteer Impact Tracking System</span>
                        </span>
                    <img id="menu-toggle" src="images/menu.png">
                </span>
            </span>
        </nav>
        <main>
            <?php
            try {
                $success = remove_person($user->get_id());
                if ($success) {
                    echo "<p class='happy-toast centered'>The account for " . $user->get_first_name() . " " . $user->get_last_name() . " has been deleted.</p>";
                } else {
                    echo "<p class='happy-toast centered'>The account for " . $user->get_first_name() . " " . $user->get_last_name() . " failed to delete.</p>";
                }
            } catch (Throwable) {
                echo "<p class='happy-toast centered'>The account requested cannot be found.  Deletion Failed.</p>";
            } 
            ?>
            <a class="button cancel" href="deleteUserSearch.php" style="margin: auto;">Delete More Users</a>
            <a class="button cancel" href="index.php" style="margin: auto;">Return to Dashboard</a>

        </main>
    </body>
</html>